# PersistentVolume - stored at /data/postgres on the minikube node
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-dev
  labels:
    environment: dev
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-dev   # path inside minikube node
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-staging
  labels:
    environment: staging
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-staging
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-prod
  labels:
    environment: prod
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-prod
  storageClassName: standard
